taxonomy_path: /app/data/V2/tech_managment_taxonomy_narrow.csv
course_path: /app/data/V2/en_course_gpt-3.5-turbo_2sent_n0_mixed_narrow_detailed_cleaned.json
cv_path: /app/data/V2/en_cv_gpt-3.5-turbo_1sent_n0_mixed_narrow_detailed_v1_cleaned.json
job_path: /app/data/V2/en_job_gpt-3.5-turbo_2sent_n0_mixed_narrow_detailed_cleaned.json
mastery_levels_path: /app/data/V2/mastery_levels.json
results_path: /app/results/frej
level_3: false
nb_courses: 100
nb_cvs: 50
nb_jobs: 100
seed: 42