taxonomy_path: data/V1/tech_managment_taxonomy_narrow.csv
course_path: data/V1/coco_courses_tech_english.json
cv_path: data/V1/kaggle_cvs.json
job_path: data/V1/tech_jobs_english.json
mastery_levels_path: data/V1/mastery_levels.json
results_path: data/V1/results
nb_courses: 100
nb_cvs: 50
nb_jobs: 100
seed: 42