taxonomy_path: data/V1/tech_managment_taxonomy_narrow.csv
course_path: data/V1/coco_courses_tech_english.json
cv_path: data/V1/kaggle_cvs.json
job_path: data/V1/tech_jobs_english.json
mastery_levels_path: data/V1/mastery_levels.json
results_path: data/V1/results
level_3: false
nb_courses: -1
nb_cvs: -1
nb_jobs: -1
seed: 42