taxonomy_path: ../data/V1/taxonomy/tech_managment_taxonomy_narrow.csv
courses_path: ../data/V1/coco_courses_tech_english.json
cv_path: ../data/V1/kaggle_cvs.json
job_path: ../data/V1/tech_jobs_english.json
