taxonomy_path: data/taxonomy.csv
course_path: data/courses.json
cv_path: data/resumes.json
job_path: data/jobs.json
mastery_levels_path: data/mastery_levels.json
results_path: results
level_3: true
nb_courses: 100
nb_cvs: -1
max_cv_skills: 15
nb_jobs: 100
threshold: 0.8
k: 2
model: ppo
total_steps: 5000
eval_freq: 1000
nb_runs: 1
seed: 42